import * as fs from 'node:fs/promises';
import * as os from 'node:os';
import * as path from 'node:path';

const { SCENE_MANIFEST, hasExpoSceneDelegate, patchAppDelegate, withUIScene } = require('../../plugin/ui-scene');
const { withMobileFoundation } = require('../../plugin');

/** AppDelegate.swift as generated by expo-template-bare-minimum for SDK 57 (trimmed to the relevant parts). */
const TEMPLATE_APP_DELEGATE = `internal import Expo
import React
import ReactAppDependencyProvider

@main
class AppDelegate: ExpoAppDelegate {
  var window: UIWindow?

  var reactNativeDelegate: ExpoReactNativeFactoryDelegate?
  var reactNativeFactory: RCTReactNativeFactory?

  public override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil
  ) -> Bool {
    let delegate = ReactNativeDelegate()
    let factory = ExpoReactNativeFactory(delegate: delegate)
    delegate.dependencyProvider = RCTAppDependencyProvider()

    reactNativeDelegate = delegate
    reactNativeFactory = factory

#if os(iOS) || os(tvOS)
    window = UIWindow(frame: UIScreen.main.bounds)
    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions)
#endif

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  // Linking API
  public override func application(
    _ app: UIApplication,
    open url: URL,
    options: [UIApplication.OpenURLOptionsKey: Any] = [:]
  ) -> Bool {
    return super.application(app, open: url, options: options) || RCTLinkingManager.application(app, open: url, options: options)
  }
}

class ReactNativeDelegate: ExpoReactNativeFactoryDelegate {
  override func bundleURL() -> URL? {
    return Bundle.main.url(forResource: "main", withExtension: "jsbundle")
  }
}
`;

const withExpo = { expoSceneDelegate: true };
const standalone = { expoSceneDelegate: false };

const baseConfig = () => ({ name: 'PluginTest', slug: 'plugin-test', ios: { bundleIdentifier: 'app.example.test' } });

const modRequest = (platformProjectRoot: string) => ({
    introspect: false,
    platform: 'ios',
    platformProjectRoot,
    projectRoot: path.dirname(platformProjectRoot),
    projectName: 'PluginTest',
});

describe('patchAppDelegate (Expo ships ExpoAppSceneDelegate)', () => {
    it('subclasses ExpoAppSceneDelegate and exposes the factory through ExpoReactNativeFactoryProvider', () => {
        const out = patchAppDelegate(TEMPLATE_APP_DELEGATE, withExpo);

        expect(out).toContain('class AppDelegate: ExpoAppDelegate, ExpoReactNativeFactoryProvider {');
        expect(out).toContain('class SceneDelegate: ExpoAppSceneDelegate {}');
        expect(out).not.toContain('UIWindow(frame: UIScreen.main.bounds)');
        expect(out).not.toContain('UIWindowSceneDelegate'); // Expo's base class does the forwarding
        // the rest of the template survives untouched
        expect(out).toContain('return super.application(application, didFinishLaunchingWithOptions: launchOptions)');
        expect(out).toContain('class ReactNativeDelegate: ExpoReactNativeFactoryDelegate');
    });

    it('relies on the "main" default module name and overrides it otherwise', () => {
        expect(patchAppDelegate(TEMPLATE_APP_DELEGATE, withExpo)).not.toContain('reactNativeFactoryModuleName');

        const custom = patchAppDelegate(TEMPLATE_APP_DELEGATE.replace('withModuleName: "main"', 'withModuleName: "custom"'), withExpo);
        expect(custom).toContain('var reactNativeFactoryModuleName: String { "custom" }');
    });
});

describe('patchAppDelegate (standalone scene delegate)', () => {
    it('moves window creation into a self-contained SceneDelegate', () => {
        const out = patchAppDelegate(TEMPLATE_APP_DELEGATE, standalone);

        expect(out).not.toContain('UIWindow(frame: UIScreen.main.bounds)');
        expect(out).toContain('self.launchOptions = launchOptions');
        expect(out).toContain('var launchOptions: [UIApplication.LaunchOptionsKey: Any]?');
        expect(out).toContain('class SceneDelegate: UIResponder, UIWindowSceneDelegate');
        expect(out).toContain('let window = UIWindow(windowScene: windowScene)');
        expect(out).toContain('class AppDelegate: ExpoAppDelegate {'); // no protocol needed without Expo's base class
        expect(out).toContain('return super.application(application, didFinishLaunchingWithOptions: launchOptions)');
    });

    it('keeps the module name the template started React Native with', () => {
        const out = patchAppDelegate(TEMPLATE_APP_DELEGATE.replace('withModuleName: "main"', 'withModuleName: "custom"'), standalone);
        expect(out).toContain('factory.startReactNative(withModuleName: "custom", in: window, launchOptions: launchOptions)');
        expect(out).not.toContain('withModuleName: "main"');
    });

    it('forwards scene life-cycle events, links, activities and quick actions to the app delegate', () => {
        const out = patchAppDelegate(TEMPLATE_APP_DELEGATE, standalone);
        for (const forwarded of [
            'applicationDidBecomeActive?(',
            'applicationWillResignActive?(',
            'applicationWillEnterForeground?(',
            'applicationDidEnterBackground?(',
            'openURLContexts URLContexts: Set<UIOpenURLContext>',
            'continue userActivity: NSUserActivity',
            'performActionFor shortcutItem: UIApplicationShortcutItem',
            'connectionOptions.shortcutItem',
            'func sceneDidDisconnect(',
        ]) {
            expect(out).toContain(forwarded);
        }
        // cold-start links reach both Linking.getInitialURL() (launch options) and the app delegate's subscribers
        expect(out).toContain('"UIApplicationLaunchOptionsURLKey")] = url');
        expect(out).toContain('"UIApplicationLaunchOptionsUserActivityKey": activity');
        expect(out).toContain('connectionOptions.urlContexts.forEach { open(url: $0.url');
        expect(out).toContain('connectionOptions.userActivities.forEach { continueUserActivity($0) }');
    });
});

describe('patchAppDelegate (guards)', () => {
    it('is idempotent in both modes', () => {
        for (const options of [withExpo, standalone]) {
            const once = patchAppDelegate(TEMPLATE_APP_DELEGATE, options);
            expect(patchAppDelegate(once, options)).toBe(once);
        }
    });

    it('leaves an app that already adopts scenes untouched, whichever delegate it uses', () => {
        for (const adoption of [
            '\nclass MyScenes: UIResponder, UIWindowSceneDelegate {}\n',
            '\nclass SceneDelegate: ExpoAppSceneDelegate {}\n',
        ]) {
            // even without the template's window bootstrap, an existing scene delegate means "skip", not "throw"
            const custom = TEMPLATE_APP_DELEGATE.replace('UIWindow(frame: UIScreen.main.bounds)', 'MyWindow()') + adoption;
            expect(patchAppDelegate(custom, withExpo)).toBe(custom);
            expect(patchAppDelegate(custom, standalone)).toBe(custom);
        }
    });

    it('fails loudly when the template bootstrap is not recognised', () => {
        const unknown = TEMPLATE_APP_DELEGATE.replace('UIWindow(frame: UIScreen.main.bounds)', 'MyWindow()');
        expect(() => patchAppDelegate(unknown, withExpo)).toThrow(/could not find the Expo template window bootstrap/);
    });
});

describe('hasExpoSceneDelegate', () => {
    it('reflects whether the resolved expo package ships ExpoAppSceneDelegate.swift', async () => {
        const root = await fs.mkdtemp(path.join(os.tmpdir(), 'mf-ui-scene-expo-'));
        const expoDir = path.join(root, 'node_modules', 'expo');
        await fs.mkdir(path.join(expoDir, 'ios', 'AppDelegates'), { recursive: true });
        await fs.writeFile(path.join(expoDir, 'package.json'), '{"name":"expo","version":"57.0.24"}');

        expect(hasExpoSceneDelegate(root)).toBe(false);
        await fs.writeFile(path.join(expoDir, 'ios', 'AppDelegates', 'ExpoAppSceneDelegate.swift'), '');
        expect(hasExpoSceneDelegate(root)).toBe(true);

        await fs.rm(root, { recursive: true, force: true });
    });

    it('is false when expo cannot be resolved at all', () => {
        expect(hasExpoSceneDelegate('/nonexistent/project')).toBe(false);
    });
});

describe('withUIScene', () => {
    it('adds a single-window scene manifest to Info.plist', async () => {
        const config = withUIScene(baseConfig());
        const result = await config.mods.ios.infoPlist({
            ...config,
            modRequest: modRequest('/tmp/ios'),
            modResults: { CFBundleName: 'PluginTest' },
        });

        expect(result.modResults.UIApplicationSceneManifest).toEqual(SCENE_MANIFEST);
        expect(result.modResults.UIApplicationSceneManifest.UISceneConfigurations.UIWindowSceneSessionRoleApplication[0].UISceneDelegateClassName)
            .toBe('$(PRODUCT_MODULE_NAME).SceneDelegate');
        expect(result.modResults.CFBundleName).toBe('PluginTest');
    });

    it('keeps an existing scene manifest', async () => {
        const config = withUIScene(baseConfig());
        const existing = { UIApplicationSupportsMultipleScenes: true };
        const result = await config.mods.ios.infoPlist({
            ...config,
            modRequest: modRequest('/tmp/ios'),
            modResults: { UIApplicationSceneManifest: existing },
        });

        expect(result.modResults.UIApplicationSceneManifest).toBe(existing);
    });

    it('rewrites the generated AppDelegate.swift on disk, picking the mode from the resolved expo package', async () => {
        const root = await fs.mkdtemp(path.join(os.tmpdir(), 'mf-ui-scene-'));
        const iosRoot = path.join(root, 'ios');
        const appDelegatePath = path.join(iosRoot, 'PluginTest', 'AppDelegate.swift');
        await fs.mkdir(path.dirname(appDelegatePath), { recursive: true });
        await fs.writeFile(appDelegatePath, TEMPLATE_APP_DELEGATE);

        // no expo resolvable from this temp project → standalone delegate
        const config = withUIScene(baseConfig());
        await config.mods.ios.dangerous({ ...config, modRequest: modRequest(iosRoot), modResults: {} });
        expect(await fs.readFile(appDelegatePath, 'utf8')).toBe(patchAppDelegate(TEMPLATE_APP_DELEGATE, standalone));

        // with an expo that ships ExpoAppSceneDelegate → subclass it
        await fs.writeFile(appDelegatePath, TEMPLATE_APP_DELEGATE);
        const expoDir = path.join(root, 'node_modules', 'expo');
        await fs.mkdir(path.join(expoDir, 'ios', 'AppDelegates'), { recursive: true });
        await fs.writeFile(path.join(expoDir, 'package.json'), '{"name":"expo","version":"57.0.24"}');
        await fs.writeFile(path.join(expoDir, 'ios', 'AppDelegates', 'ExpoAppSceneDelegate.swift'), '');
        await config.mods.ios.dangerous({ ...config, modRequest: modRequest(iosRoot), modResults: {} });
        expect(await fs.readFile(appDelegatePath, 'utf8')).toBe(patchAppDelegate(TEMPLATE_APP_DELEGATE, withExpo));

        await fs.rm(root, { recursive: true, force: true });
    });

    it('explains itself when there is no Swift app delegate to patch', async () => {
        const root = await fs.mkdtemp(path.join(os.tmpdir(), 'mf-ui-scene-missing-'));
        const config = withUIScene(baseConfig());
        await expect(
            config.mods.ios.dangerous({ ...config, modRequest: modRequest(path.join(root, 'ios')), modResults: {} }),
        ).rejects.toThrow(/expects a Swift app delegate/);
        await fs.rm(root, { recursive: true, force: true });
    });
});

describe('combined plugin', () => {
    it('applies the UIScene plugin by default', () => {
        const config = withMobileFoundation(baseConfig(), {});
        expect(config.mods?.ios?.infoPlist).toBeDefined();
        expect(config.mods?.ios?.dangerous).toBeDefined();
    });

    it('can opt out with uiScene: false', () => {
        const config = withMobileFoundation(baseConfig(), { uiScene: false });
        expect(config.mods?.ios).toBeUndefined();
    });
});
