const fs = require("node:fs/promises");
const { existsSync } = require("node:fs");
const path = require("node:path");

const {
    createRunOncePlugin,
    withDangerousMod,
    withInfoPlist,
} = require("expo/config-plugins");

const PACKAGE = require("../package.json");
const PLUGIN_NAME = `${PACKAGE.name}/ui-scene`;

/**
 * UIScene life-cycle adoption for Expo (prebuild) apps.
 *
 * The iOS 27 SDK refuses to launch apps that still use the app-delegate life cycle
 * ("Application failed to launch: UIScene life cycle is required for apps built with this SDK").
 * Expo SDK 57's bare template has not adopted scenes, so this plugin:
 *
 *   1. registers a single window-scene configuration in Info.plist (UIApplicationSceneManifest), and
 *   2. rewrites the generated AppDelegate.swift so the window is created — and React Native started —
 *      from a `SceneDelegate` instead of application(_:didFinishLaunchingWithOptions:).
 *
 * When the installed `expo` package ships `ExpoAppSceneDelegate` (57.0.2x+), the generated scene
 * delegate simply subclasses it and the app delegate conforms to `ExpoReactNativeFactoryProvider`, so
 * Expo owns the event forwarding. Older Expo versions get a self-contained scene delegate that forwards
 * life-cycle events, URLs, user activities and quick actions to the app delegate itself.
 *
 * Both edits are idempotent and skipped when the project already adopts scenes.
 */

const SCENE_MANIFEST = {
    UIApplicationSupportsMultipleScenes: false,
    UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
            {
                UISceneConfigurationName: "Default Configuration",
                UISceneDelegateClassName: "$(PRODUCT_MODULE_NAME).SceneDelegate",
            },
        ],
    },
};

// The window bootstrap block from expo-template-bare-minimum (SDK 57); the module name is captured.
const WINDOW_BLOCK_PATTERN =
    /#if os\(iOS\) \|\| os\(tvOS\)\n\s*window = UIWindow\(frame: UIScreen\.main\.bounds\)\n\s*factory\.startReactNative\(\n\s*withModuleName: "([^"]+)",\n\s*in: window,\n\s*launchOptions: launchOptions\)\n#endif\n/;

const WINDOW_PROPERTY = "  var window: UIWindow?\n";
const APP_DELEGATE_CLASS = "class AppDelegate: ExpoAppDelegate {\n";

const GENERATED_HEADER = `
// MARK: - UIScene life cycle (generated by ${PLUGIN_NAME})
//
// The iOS 27 SDK refuses to launch apps that have not adopted the UIScene life cycle, and Expo's
// template still uses the app-delegate life cycle. Wired up via UIApplicationSceneManifest in Info.plist.`;

/** Scene delegate for Expo versions that ship ExpoAppSceneDelegate: Expo owns the event forwarding. */
const createExpoSceneDelegate = () => `${GENERATED_HEADER}
class SceneDelegate: ExpoAppSceneDelegate {}
`;

/** Self-contained scene delegate for Expo versions without ExpoAppSceneDelegate. */
const createStandaloneSceneDelegate = (moduleName) => `${GENERATED_HEADER}
//
// This window-scene delegate creates the window, starts React Native inside it and re-feeds scene
// events to the app delegate: under the scene life cycle UIKit no longer calls the app delegate's
// life-cycle, URL, user-activity and quick-action methods, but Expo's app-delegate subscribers and
// React Native's Linking still rely on them.
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene else { return }
    guard let appDelegate = UIApplication.shared.delegate as? AppDelegate,
          let factory = appDelegate.reactNativeFactory else {
      fatalError(
        "SceneDelegate couldn't start React Native: the app delegate must be the generated AppDelegate "
        + "and create its RCTReactNativeFactory in application(_:didFinishLaunchingWithOptions:)."
      )
    }

    let window = UIWindow(windowScene: windowScene)
    self.window = window
    // mirror the window onto the app delegate so code reading UIApplication.shared.delegate?.window keeps working
    appDelegate.window = window

    // Cold-start URLs and universal links arrive in connectionOptions rather than in the app delegate's
    // launch options, but React Native's Linking.getInitialURL() only reads launch options — rebuild them.
    // The keys are spelled out because the UIApplication.LaunchOptionsKey accessors are deprecated on iOS 26.
    var launchOptions = appDelegate.launchOptions ?? [:]
    if let url = connectionOptions.urlContexts.first?.url {
      launchOptions[UIApplication.LaunchOptionsKey(rawValue: "UIApplicationLaunchOptionsURLKey")] = url
    }
    if let activity = connectionOptions.userActivities.first(where: { $0.activityType == NSUserActivityTypeBrowsingWeb }) {
      launchOptions[UIApplication.LaunchOptionsKey(rawValue: "UIApplicationLaunchOptionsUserActivityDictionaryKey")] = [
        "UIApplicationLaunchOptionsUserActivityTypeKey": activity.activityType,
        "UIApplicationLaunchOptionsUserActivityKey": activity,
      ]
    }

    factory.startReactNative(withModuleName: "${moduleName}", in: window, launchOptions: launchOptions)

    // Re-feed cold-start links, activities and quick actions to the app delegate (and its subscribers).
    connectionOptions.urlContexts.forEach { open(url: $0.url, options: Self.openURLOptions(from: $0.options)) }
    connectionOptions.userActivities.forEach { continueUserActivity($0) }
#if os(iOS)
    if let shortcutItem = connectionOptions.shortcutItem {
      perform(shortcutItem) { _ in }
    }
#endif
  }

  func sceneDidDisconnect(_ scene: UIScene) {
    window = nil
  }

  // Foreground/background transitions
  func sceneDidBecomeActive(_ scene: UIScene) {
    UIApplication.shared.delegate?.applicationDidBecomeActive?(UIApplication.shared)
  }

  func sceneWillResignActive(_ scene: UIScene) {
    UIApplication.shared.delegate?.applicationWillResignActive?(UIApplication.shared)
  }

  func sceneWillEnterForeground(_ scene: UIScene) {
    UIApplication.shared.delegate?.applicationWillEnterForeground?(UIApplication.shared)
  }

  func sceneDidEnterBackground(_ scene: UIScene) {
    UIApplication.shared.delegate?.applicationDidEnterBackground?(UIApplication.shared)
  }

  // Linking API
  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    URLContexts.forEach { open(url: $0.url, options: Self.openURLOptions(from: $0.options)) }
  }

  // Universal Links
  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    continueUserActivity(userActivity)
  }

#if os(iOS)
  // Quick actions (home-screen shortcuts)
  func windowScene(
    _ windowScene: UIWindowScene,
    performActionFor shortcutItem: UIApplicationShortcutItem,
    completionHandler: @escaping (Bool) -> Void
  ) {
    perform(shortcutItem, completionHandler: completionHandler)
  }
#endif

  // The app delegate's own overrides already notify RCTLinkingManager, so it is not called here too.
  private func open(url: URL, options: [UIApplication.OpenURLOptionsKey: Any]) {
    _ = UIApplication.shared.delegate?.application?(UIApplication.shared, open: url, options: options)
  }

  private func continueUserActivity(_ userActivity: NSUserActivity) {
    _ = UIApplication.shared.delegate?.application?(
      UIApplication.shared,
      continue: userActivity,
      restorationHandler: { _ in }
    )
  }

#if os(iOS)
  private func perform(_ shortcutItem: UIApplicationShortcutItem, completionHandler: @escaping (Bool) -> Void) {
    guard let delegate = UIApplication.shared.delegate,
          delegate.responds(to: #selector(UIApplicationDelegate.application(_:performActionFor:completionHandler:))) else {
      completionHandler(false)
      return
    }
    delegate.application?(UIApplication.shared, performActionFor: shortcutItem, completionHandler: completionHandler)
  }
#endif

  private static func openURLOptions(from sceneOptions: UIScene.OpenURLOptions) -> [UIApplication.OpenURLOptionsKey: Any] {
    var options: [UIApplication.OpenURLOptionsKey: Any] = [:]
    if let sourceApplication = sceneOptions.sourceApplication {
      options[.sourceApplication] = sourceApplication
    }
    if let annotation = sceneOptions.annotation {
      options[.annotation] = annotation
    }
    options[.openInPlace] = sceneOptions.openInPlace
    return options
  }
}
`;

/** True when the project already adopts the UIScene life cycle — our output, Expo's, or the app's own. */
const hasSceneAdoption = (source) => /SceneDelegate/.test(source);

/**
 * Pure transformation of the template's AppDelegate.swift. Exported so it can be unit tested and
 * applied by hand to an existing native project.
 *
 * @param {string} source AppDelegate.swift contents
 * @param {{ expoSceneDelegate: boolean }} options whether the installed Expo ships ExpoAppSceneDelegate
 */
const patchAppDelegate = (source, { expoSceneDelegate }) => {
    if (hasSceneAdoption(source)) {
        return source;
    }

    const match = WINDOW_BLOCK_PATTERN.exec(source);
    if (match === null || !source.includes(WINDOW_PROPERTY) || !source.includes(APP_DELEGATE_CLASS)) {
        throw new Error(
            `${PLUGIN_NAME} could not find the Expo template window bootstrap in AppDelegate.swift. ` +
                "Adopt the UIScene life cycle in the app itself and disable this plugin with `uiScene: false`.",
        );
    }
    const moduleName = match[1];

    if (expoSceneDelegate) {
        let contents = source.replace(
            WINDOW_BLOCK_PATTERN,
            "    // the window is created once UIKit connects our scene (see SceneDelegate below)\n",
        );
        contents = contents.replace(
            APP_DELEGATE_CLASS,
            "class AppDelegate: ExpoAppDelegate, ExpoReactNativeFactoryProvider {\n",
        );
        if (moduleName !== "main") {
            contents = contents.replace(
                WINDOW_PROPERTY,
                `${WINDOW_PROPERTY}  var reactNativeFactoryModuleName: String { "${moduleName}" }\n`,
            );
        }
        return contents.replace(/\n*$/, "\n") + createExpoSceneDelegate();
    }

    let contents = source.replace(
        WINDOW_BLOCK_PATTERN,
        "    // the window is created once UIKit connects our scene (see SceneDelegate below)\n" +
            "    self.launchOptions = launchOptions\n",
    );
    contents = contents.replace(
        WINDOW_PROPERTY,
        `${WINDOW_PROPERTY}  var launchOptions: [UIApplication.LaunchOptionsKey: Any]?\n`,
    );
    return contents.replace(/\n*$/, "\n") + createStandaloneSceneDelegate(moduleName);
};

/**
 * Whether the `expo` package the app resolves ships ExpoAppSceneDelegate (Expo 57.0.2x and later).
 * Walks the node_modules chain like Node's resolver would, without going through `require.resolve`
 * (whose results are cached, which matters for monorepos and for tests).
 */
const hasExpoSceneDelegate = (projectRoot) => {
    let directory = path.resolve(projectRoot);
    for (;;) {
        const candidate = path.join(
            directory,
            "node_modules",
            "expo",
            "ios",
            "AppDelegates",
            "ExpoAppSceneDelegate.swift",
        );
        if (existsSync(candidate)) {
            return true;
        }
        const parent = path.dirname(directory);
        if (parent === directory) {
            return false;
        }
        directory = parent;
    }
};

const withSceneManifest = (config) =>
    withInfoPlist(config, (modConfig) => {
        if (modConfig.modResults.UIApplicationSceneManifest === undefined) {
            modConfig.modResults.UIApplicationSceneManifest = SCENE_MANIFEST;
        }
        return modConfig;
    });

const withSceneDelegate = (config) =>
    withDangerousMod(config, [
        "ios",
        async (modConfig) => {
            const appDelegatePath = path.join(
                modConfig.modRequest.platformProjectRoot,
                modConfig.modRequest.projectName,
                "AppDelegate.swift",
            );
            if (!existsSync(appDelegatePath)) {
                throw new Error(
                    `${PLUGIN_NAME} expects a Swift app delegate at ${appDelegatePath}. ` +
                        "Adopt the UIScene life cycle in the app itself and disable this plugin with `uiScene: false`.",
                );
            }

            const contents = await fs.readFile(appDelegatePath, "utf8");
            const patched = patchAppDelegate(contents, {
                expoSceneDelegate: hasExpoSceneDelegate(modConfig.modRequest.projectRoot),
            });
            if (patched !== contents) {
                await fs.writeFile(appDelegatePath, patched);
            }
            return modConfig;
        },
    ]);

const withUIScene = (config) => {
    config = withSceneManifest(config);
    config = withSceneDelegate(config);
    return config;
};

module.exports = createRunOncePlugin(withUIScene, PLUGIN_NAME, PACKAGE.version);
module.exports.SCENE_MANIFEST = SCENE_MANIFEST;
module.exports.hasExpoSceneDelegate = hasExpoSceneDelegate;
module.exports.patchAppDelegate = patchAppDelegate;
module.exports.withUIScene = withUIScene;
