import {
    configureFoundation,
    createAppStorage,
} from '@zyno-io/mobile-foundation-rn';
import { faCheck, faSpinner } from '@fortawesome/free-solid-svg-icons';

configureFoundation({
    colors: {
        light: {
            transparent: 'transparent',
            white: '#fff',
            black: '#000',
            background: '#fff',
            surface: '#f5f5f5',
            text: '#000',
            secondaryText: '#666',
            accent: '#007AFF',
            primaryButtonBackground: '#007AFF',
            primaryButtonText: '#fff',
            secondaryButtonBackground: '#e5e5e5',
            secondaryButtonText: '#000',
            cardBackground: '#fff',
            cardBorder: '#ddd',
            cardText: '#000',
            cardSecondaryText: '#666',
            cardTertiaryText: '#999',
            fieldLabel: '#666',
            inputBackground: '#f5f5f5',
            inputInvalidBackground: '#fee',
            inputText: '#000',
            inputIcon: '#999',
            inputPlaceholderText: '#999',
            selectedItemBackground: '#007AFF',
            selectedItemBorder: '#007AFF',
            selectedItemText: '#fff',
            infoText: '#666',
            dangerBackground: '#fee',
            dangerButtonBackground: '#ff3b30',
            dangerButtonText: '#fff',
        },
        dark: {
            transparent: 'transparent',
            white: '#fff',
            black: '#000',
            background: '#1c1c1e',
            surface: '#2c2c2e',
            text: '#fff',
            secondaryText: '#aeaeb2',
            accent: '#0a84ff',
            primaryButtonBackground: '#0a84ff',
            primaryButtonText: '#fff',
            secondaryButtonBackground: '#3a3a3c',
            secondaryButtonText: '#fff',
            cardBackground: '#2c2c2e',
            cardBorder: '#3a3a3c',
            cardText: '#fff',
            cardSecondaryText: '#aeaeb2',
            cardTertiaryText: '#636366',
            fieldLabel: '#aeaeb2',
            inputBackground: '#2c2c2e',
            inputInvalidBackground: '#3a1a1a',
            inputText: '#fff',
            inputIcon: '#636366',
            inputPlaceholderText: '#636366',
            selectedItemBackground: '#0a84ff',
            selectedItemBorder: '#0a84ff',
            selectedItemText: '#fff',
            infoText: '#aeaeb2',
            dangerBackground: '#3a1a1a',
            dangerButtonBackground: '#ff453a',
            dangerButtonText: '#fff',
        },
    },
    env: {
        APP_ENV: 'test',
        BUILD_VERSION: '1.0.0-test',
        CDN_URL: 'https://cdn.test.com',
    },
    icons: {
        check: faCheck,
        spinner: faSpinner,
    },
});

createAppStorage({});
